---
# Add utility packages to all vms
- hosts: all_vms
  vars_files:
    - vars/all.yml
  roles:
    - { role: vm-utilities }

# Set Quagga.conf for router a
# Statically routing requests to centos B to router B
- hosts: router_a
  vars_files:
    - vars/all.yml
  roles:
    - { role: quagga-config, route_mask: "{{ hostvars['centos_b']['ansible_host'] }}/32", route_via: "{{ hostvars['router_b']['ansible_host'] }}" }

# Set a static route on centos A for centos B to route through router a
- hosts: centos_a
  vars_files:
    - vars/all.yml
  tasks:
    - name: Set the static route on centos_a to centos_b
      shell: >
        route add -net {{ hostvars['centos_b']['ansible_host'] }} netmask 255.255.255.255 gw {{ hostvars['router_a']['ansible_host'] }}
      ignore_errors: yes

# Run quagga in a container on all vms
- hosts: routers
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: docker-install }
    - { role: quagga-run, force_quagga_kill: true }