---

- name: Template quagga config
  template: 
    src: Quagga.conf.j2
    dest: "{{ destination_config }}"

- name: Template ospfd config
  template: 
    src: ospfd.conf.j2
    dest: "{{ destination_ospfd_config }}"

- name: Template quagga config
  template: 
    src: daemons.j2
    dest: /etc/quagga.daemons

- name: List docker images
  shell: >
    docker images
  register: docker_images

- name: Always setup iptables forwarding rules
  shell: >
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
    iptables -A FORWARD -i eth0 -j ACCEPT

- name: Kill and remove quagga, conditionally
  shell: >
    docker kill {{ quagga_container_name }}
  when: "force_quagga_kill"
  ignore_errors: yes

- name: Get list of running containers
  # Single quotes were messing up my conditional below...
  shell: >
    docker ps -a | sed -e "s/'//"
  register: docker_psa

- name: Default volume fact
  set_fact:
    config_mount: ""

- name: Set volume fact when necessary
  set_fact:
    config_mount: "-v {{ use_config }}:/etc/quagga/Quagga.conf"
  when: use_config is defined

- name: Run quagga if not yet running
  # 
  shell: >
    docker run -dt 
    --name {{ quagga_container_name }} 
    -h {{ quagga_container_name }} 
    {{ config_mount }} 
    -v /etc/quagga.daemons:/etc/quagga/daemons
    -v {{ destination_ospfd_config }}:/etc/quagga/ospfd.conf
    --privileged 
    --net none 
    {{ quagga_image_name }}

- name: set quagga static routes
  shell: >
    docker exec -i {{ quagga_container_name }} 
    vtysh
    -c 'config term' 
    -c 'ip route {{ item }}'
    -c 'router ospf' 
    -c 'redistribute stat'
  with_items: "{{ quagga_static_route }}"

