---
# Run 2 quagga instances in containers on all vms
- hosts: all_vms
  vars_files:
    - vars/all.yml
  pre_tasks:
    - name: Remove all running containers
      shell: >
        docker rm $(docker kill $(docker ps -aq))
      ignore_errors: yes
  tasks: []
  roles:
    - { role: docker-install }
    - { role: build-quagga }
    - { role: koko-compile }
    - { role: docker-build-images }
    - { role: run-endpoints }
    - { role: quagga-run,
        quagga_container_name: quagga_a,
        force_quagga_kill: true,
        quagga_debug: true,
        # use_config: "/etc/quagga_a.conf",
        ospfd_passive_interface: "in2",
        ospfd_interfaces: [in2, mid1],
        ospfd_networks: ["192.168.2.0/24","192.168.3.0/24","2.2.2.0/24","3.3.3.0/24"],
        destination_config: "/etc/quagga_a.conf",
        destination_ospfd_config: "/etc/quagga_ospfd_a.conf",
        route_mask: "192.168.4.101/32",
        route_via: "192.168.3.101",
        router_id: "2.2.2.2",
        quagga_static_route: "1.1.1.1 255.255.255.255 192.168.2.100",
      }
    - { role: quagga-run,
        quagga_container_name: quagga_b,
        force_quagga_kill: true,
        quagga_debug: true,
        # use_config: "/etc/quagga_b.conf",
        ospfd_passive_interface: "out1",
        ospfd_interfaces: [mid2, out1],
        ospfd_networks: ["192.168.3.0/24", "192.168.4.0/24","2.2.2.0/24","3.3.3.0/24"],
        destination_config: "/etc/quagga_b.conf",
        destination_ospfd_config: "/etc/quagga_ospfd_b.conf",
        route_mask: "192.168.4.101/32",
        route_via: "192.168.4.101",
        classa_route_mask: "4.4.4.4/32",
        router_id: "3.3.3.3",
        quagga_static_route: "4.4.4.4 255.255.255.255 192.168.4.101",
       }
    - { role: koko-configure }