---
- name: Template router pods yaml
  template:
    src: router_pods.yaml.j2
    dest: /etc/router_pods.yaml

- name: Template router SCC
  template:
    src: router_scc.yaml.j2
    dest: /etc/router_scc.yaml

- name: Create SCC & pods
  shell: >
    oc create -f /etc/router_scc.yaml;
    oc create -f /etc/router_pods.yaml