---
# ---------------------------------
# Connections.
# centos_a -> quagga_a (in1, in2)
# quagga_a -> quagga_b (mid1, mid2)
# quagga_b -> centos_b (out1, out2)

- name: Get centos_a ID
  shell: >
    docker ps | grep centos_a | awk '{print $1}'
  register: id_centos_a

- name: Get centos_b ID
  shell: >
    docker ps | grep centos_b | awk '{print $1}'
  register: id_centos_b

- name: Get quagga_a ID
  shell: >
    docker ps | grep quagga_a | awk '{print $1}'
  register: id_quagga_a

- name: Get quagga_b ID
  shell: >
    docker ps | grep quagga_b | awk '{print $1}'
  register: id_quagga_b

- debug: "msg={{ id_centos_a.stdout }}"
- debug: "msg={{ id_centos_b.stdout }}"
- debug: "msg={{ id_quagga_a.stdout }}"
- debug: "msg={{ id_quagga_b.stdout }}"

- name: Create ingress interfaces
  shell: >
    /usr/src/gocode/vethcon {{ id_centos_a.stdout }} {{ id_quagga_a.stdout }} in1 in2

- name: Create middle interfaces
  shell: >
    /usr/src/gocode/vethcon {{ id_quagga_a.stdout }} {{ id_quagga_b.stdout }} mid1 mid2

- name: Create egress interfaces
  shell: >
    /usr/src/gocode/vethcon {{ id_quagga_b.stdout }} {{ id_centos_b.stdout }} out1 out2

# [root@cd23ab1e4135 /]# ip link set dev test2 up
# [root@cd23ab1e4135 /]# ip a add 192.168.5.200/255.255.255.0 dev test2

- name: Bring up centos_a interfaces
  shell: >
    docker exec -i centos_a /bin/bash -c '
    ip link set dev in1 up;
    ip a add 192.168.2.100/255.255.255.0 dev in1
    '

- name: Bring up quagga_a interfaces
  shell: >
    docker exec -i quagga_a /bin/bash -c '
    ip link set dev in2 up;
    ip a add 192.168.2.101/255.255.255.0 dev in2;
    ip link set dev mid1 up;
    ip a add 192.168.3.100/255.255.255.0 dev mid1;
    '

- name: Bring up quagga_b interfaces
  shell: >
    docker exec -i quagga_b /bin/bash -c '
    ip link set dev mid2 up;
    ip a add 192.168.3.101/255.255.255.0 dev mid2;
    ip link set dev out1 up;
    ip a add 192.168.4.100/255.255.255.0 dev out1;
    '

- name: Bring up centos_b interfaces
  shell: >
    docker exec -i centos_b /bin/bash -c '
    ip link set dev out2 up;
    ip a add 192.168.4.101/255.255.255.0 dev out2;
    '

# [root@372db007d004 /]# ip route add 192.168.4.0/24 via 192.168.2.101 dev in1
# [root@372db007d004 /]# 
# [root@372db007d004 /]# 
# [root@372db007d004 /]# 
# [root@372db007d004 /]# route -n

# apt-get update
# apt-get install inetutils-ping net-tools tcpdump