---

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - nano 
    - tree 
    - git

- name: Import go-repo.io gpg keys
  shell: >
    rpm --import https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO

- name: Add custom go-repo.io
  yum_repository:
    name: go-repo
    description: Latest Go Lang repo
    baseurl: https://mirror.go-repo.io/centos/$releasever/$basearch/

- name: Install go
  yum:
    name: golang
    state: present

- name: Setup environment variables
  set_fact:
    go_environment:
      GOPATH: "/usr/src/gocode/"

- name: Create go source directory
  file:
    path: /usr/src/gocode/src/koko
    state: directory

- name: Clone koko
  git:
    repo: 'https://github.com/redhat-nfvpe/koko.git'
    dest: /usr/src/gocode/src/koko/
    version: master

- name: Resolve koko dependencies
  shell: >
    go get koko
  args:
    creates: /usr/src/gocode/src/github.com
    chdir: /usr/src/gocode/
  environment: "{{ go_environment }}"

- name: Compile koko binary
  shell: >
    go build koko
  args:
    creates: /usr/src/gocode/koko
    chdir: /usr/src/gocode/
  environment: "{{ go_environment }}"

