---

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - golang 
    - nano 
    - tree 
    - git

- name: Setup environment variables
  set_fact:
    go_environment:
      GOPATH: "/usr/src/gocode/"

- name: Create go source directory
  file:
    path: /usr/src/gocode/src/koko
    state: directory

- name: Clone koko
  git:
    repo: 'https://github.com/redhat-nfvpe/koko.git'
    dest: /usr/src/gocode/src/koko/
    version: master

- name: Resolve koko dependencies
  shell: >
    go get koko
  args:
    creates: /usr/src/gocode/src/github.com
    chdir: /usr/src/gocode/
  environment: "{{ go_environment }}"

- name: Compile koko binary
  shell: >
    go build koko
  args:
    creates: /usr/src/gocode/koko
    chdir: /usr/src/gocode/
  environment: "{{ go_environment }}"

